### ISSUE TITLE
adviser fails with server closed the connection unexpectedly

### ISSUE THREAD

**Issue by pacospace** [thoth-station/support#12]
**Describe the bug**
adviser fails with server closed the connection unexpectedly.

**To Reproduce**
1. `pip install thamos`
2. Clone https://github.com/thoth-station/ps-cv
3. Run `thamos advise -r ps-cv-tensorflow` from root and wait for advise

**Expected behavior**
adviser delivers recommendation.

**Screenshots**
```
2021-08-19 08:22:28,518 thoth.adviser.run           ERROR: The resolution failed as an error was encountered: (psycopg2.errors.ProtocolViolation) server conn crashed?
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[SQL: SELECT DISTINCT depends_on.extra AS depends_on_extra, python_package_version_entity.package_name AS python_package_version_entity_package_name, python_package_version_entity.package_version AS python_package_version_entity_package_version 
FROM python_package_version JOIN python_package_index ON python_package_index.id = python_package_version.python_package_index_id JOIN depends_on ON python_package_version.id = depends_on.version_id JOIN python_package_version_entity ON python_package_version_entity.id = depends_on.entity_id 
WHERE python_package_version.package_name = %(package_name_1)s AND python_package_version.package_version = %(package_version_1)s AND python_package_version.os_name = %(os_name_1)s AND python_package_version.os_version = %(os_version_1)s AND python_package_version.python_version = %(python_version_1)s AND python_package_version.is_missing = false AND python_package_index.url = %(url_1)s AND depends_on.extra IS NULL AND depends_on.marker_evaluation_result = true]
[parameters: {'package_name_1': 'nbconvert', 'package_version_1': '5.4.0', 'os_name_1': 'rhel', 'os_version_1': '8', 'python_version_1': '3.8', 'url_1': 'https://pypi.org/simple'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ProtocolViolation: server conn crashed?
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/thoth/adviser/run.py", line 76, in subprocess_run
    report: Union[DependencyMonkeyReport, Report] = resolver.resolve(
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1309, in resolve
    for state in self._do_resolve_states(with_devel=with_devel, user_stack_scoring=user_stack_scoring):
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1239, in _do_resolve_states
    for final_state in self._do_resolve_states_raw(
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 1183, in _do_resolve_states_raw
    state_returned = self._expand_state(state, unresolved_package_tuple)
  File "/opt/app-root/src/thoth/adviser/resolver.py", line 854, in _expand_state
    dependencies = self.graph.get_depends_on(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 222, in cached_method
    return func(self_weak(), *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/graph/postgres.py", line 2422, in get_depends_on
    query.join(PythonPackageVersionEntity)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.ProtocolViolation) server conn crashed?
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

[SQL: SELECT DISTINCT depends_on.extra AS depends_on_extra, python_package_version_entity.package_name AS python_package_version_entity_package_name, python_package_version_entity.package_version AS python_package_version_entity_package_version 
FROM python_package_version JOIN python_package_index ON python_package_index.id = python_package_version.python_package_index_id JOIN depends_on ON python_package_version.id = depends_on.version_id JOIN python_package_version_entity ON python_package_version_entity.id = depends_on.entity_id 
WHERE python_package_version.package_name = %(package_name_1)s AND python_package_version.package_version = %(package_version_1)s AND python_package_version.os_name = %(os_name_1)s AND python_package_version.os_version = %(os_version_1)s AND python_package_version.python_version = %(python_version_1)s AND python_package_version.is_missing = false AND python_package_index.url = %(url_1)s AND depends_on.extra IS NULL AND depends_on.marker_evaluation_result = true]
[parameters: {'package_name_1': 'nbconvert', 'package_version_1': '5.4.0', 'os_name_1': 'rhel', 'os_version_1': '8', 'python_version_1': '3.8', 'url_1': 'https://pypi.org/simple'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2021-08-19 08:22:28,654 thoth.adviser.run           ERROR: Child exited with exit code 512
2021-08-19 08:22:28,659 thoth.adviser.run           ERROR: Resolution was terminated based on errors encountered; see logs for more info - https://thoth-station.ninja/j/error_logs

```

**Additional context**
check `thamos logs adviser-210819081130-bcfdc99f7ab943bd` to see all logs.

**Comment by fridex** [comment]
> ```
> sqlalchemy.exc.OperationalError: (psycopg2.errors.ProtocolViolation) server conn crashed?
> server closed the connection unexpectedly
>         This probably means the server terminated abnormally
>         before or while processing the request.
> ```

Looks like a networking issue in the cluster.

**Comment by pacospace** [comment]
> > ```
> > sqlalchemy.exc.OperationalError: (psycopg2.errors.ProtocolViolation) server conn crashed?
> > server closed the connection unexpectedly
> >         This probably means the server terminated abnormally
> >         before or while processing the request.
> > ```
> 
> Looks like a networking issue in the cluster.

But I tried three times already, the resolution is working and then it simply exits, can we do something about it?

**Comment by pacospace** [comment]
> > > ```
> > > sqlalchemy.exc.OperationalError: (psycopg2.errors.ProtocolViolation) server conn crashed?
> > > server closed the connection unexpectedly
> > >         This probably means the server terminated abnormally
> > >         before or while processing the request.
> > > ```
> > 
> > 
> > Looks like a networking issue in the cluster.
> 
> But I tried three times already, the resolution is working and then it simply exits, can we do something about it?

Is it some query taking too much time?

**Comment by fridex** [comment]
It looks like connection issues to the database:

`2021-08-19 08:46:39.913 UTC [11] WARNING C-0x16ffc88: thoth/userD7A@10.131.0.50:60490 pooler error: pgbouncer cannot connect to server`

We saw this before on moc, this was a networking issue in the cluster.

CC @harshad16

**Comment by pacospace** [comment]
> It looks like connection issues to the database:
> 
> `2021-08-19 08:46:39.913 UTC [11] WARNING C-0x16ffc88: thoth/userD7A@10.131.0.50:60490 pooler error: pgbouncer cannot connect to server`
> 
> We saw this before on moc, this was a networking issue in the cluster.
> 
> CC @harshad16

Thanks!!

With smaller stacks I'm able to receive an advise

**Comment by fridex** [comment]
> With smaller stacks I'm able to receive an advise

Might be some network hiccup in the cluster, I doubt this is an error on the application layer we could handle.

**Comment by pacospace** [comment]
> > With smaller stacks I'm able to receive an advise
> 
> Might be some network hiccup in the cluster, I doubt this is an error on the application layer we could handle.

I see similar erros also in some solvers :/
