### ISSUE TITLE
aggregator in security indicators fails on si-bandit key error in stage

### ISSUE THREAD

**Issue by fridex** [thoth-station/support#13]
**Describe the bug**

Security indicator workflow fails on key error:

```
{"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1629369069.1329303, "asctime": "2021-08-19 10:31:09,132", "msecs": 132.93027877807617, "relative_created": 14198.49944114685, "process": 1, "message": "Logging to a Sentry instance is turned off"}
Traceback (most recent call last):
  File "app.py", line 153, in <module>
    __name__ == "__main__" and si_aggregator()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "app.py", line 134, in si_aggregator
    out = agg_func(si_bandit_results=si_bandit_results, si_cloc_results=si_cloc_results)
  File "/opt/app-root/src/aggregators.py", line 71, in process_data
    si_bandit_report=si_bandit_results, si_cloc_report=si_cloc_results, filters_files=["/test"], output_json=True
  File "/opt/app-root/lib/python3.6/site-packages/thoth/report_processing/components/security.py", line 823, in create_si_aggregated_results
    si_bandit_report=si_bandit_report, filters_files=filters_files, analyzer_version=si_bandit_version
  File "/opt/app-root/lib/python3.6/site-packages/thoth/report_processing/components/security.py", line 458, in create_si_bandit_final_dataframe
    si_bandit_report=si_bandit_report, analyzer_version=analyzer_version
  File "/opt/app-root/lib/python3.6/site-packages/thoth/report_processing/components/security.py", line 295, in create_si_bandit_metadata_dataframe
    metadata_si_bandit = self._extract_data_from_si_bandit_metadata(si_bandit_report=si_bandit_report)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/report_processing/components/security.py", line 270, in _extract_data_from_si_bandit_metadata
    "package_name": report_metadata["arguments"]["si-bandit"]["package_name"],
KeyError: 'si-bandit'
```

**To Reproduce**
1. Run security indicators in stage environment
2. See the error

**Expected behavior**

Security indicators should succeed.

**Comment by goern** [comment]
@KPostOffice could you triage this? give it a prio etc?

**Comment by KPostOffice** [comment]
caused by the following PR https://github.com/thoth-station/si-bandit/pull/22

`si-bandit` represents the name of the script being run in metadata but after this change it should be `app.py`

**Comment by KPostOffice** [comment]
/close
fixed by the above PR
