### ISSUE TITLE
Kebechet thoth-advise manager: ConnectionError on kebechet_runners.py:210

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/support#134]
## Description
This is an automated issue generated by Kebechet. The thoth-advise manager threw an exception (ConnectionError) at
runtime while working on the following repository https://github.com/KPostOffice/khebhut_test

## Traceback
```python
Traceback (most recent call last):
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f13fcff1df0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f13fcff1df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 448, in run
    analysis_id = lib.advise_here(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/thamos/lib.py", line 666, in advise_here
    return advise(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/thamos/lib.py", line 101, in wrapper
    thoth_config.api_discovery(host)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/thamos/config.py", line 480, in api_discovery
    response = requests.get(
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f13fcff1df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

```

**Comment by goern** [comment]
/kind bug
or is this a feature to not raise the exception and generate some metric?!
/priority important-soon
/assign @KPostOffice 
/triage accepted

**Comment by KPostOffice** [comment]
Hmmm, good question. It may be useful to open an issue in the user's repo in this case with the text: "Connection Error when connecting to host url, please check to make sure that the url is correct. If it is correct then thoth-services may be down".  Do we have a dashboard where users can see what services are available? i.e. external facing user-api at khemenu.thoth-station.ninja is down?

**Comment by codificat** [comment]
As there have been a few instances of connection errors, an umbrella issue has been raised about this: #168.

**Comment by codificat** [comment]
/close
in favour of #168
