### ISSUE TITLE
Kebechet thoth-advise manager: AttributeError on kebechet_runners.py:202

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/support#136]
## Description
This is an automated issue generated by Kebechet. The thoth-advise manager threw an exception (AttributeError) at
runtime while working on the following repository https://github.com/KPostOffice/khebhut_test

## Traceback
```python
Traceback (most recent call last):
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/kebechet_runners.py", line 202, in run
    instance = kebechet_manager(
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 101, in __init__
    self._tracking_issue  # if a Kebechet Advise issue is found it will be commented on to track progress
AttributeError: 'ThothAdviseManager' object has no attribute '_tracking_issue'

```

**Comment by KPostOffice** [comment]
Opened during local testing. I think it may be good to make automatic issue reporting configurable so that we don't open issues on the support repo during local testing
