### ISSUE TITLE
Kebechet thoth-advise manager: KeyError on kebechet_runners.py:210

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/support#137]
## Description
This is an automated issue generated by Kebechet. The thoth-advise manager threw an exception (KeyError) at
runtime while working on the following repository https://github.com/KPostOffice/khebhut_test

## Traceback
```python
Traceback (most recent call last):
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 353, in run
    STARTED_ADVISE_COMMENT.format(
KeyError: 'environment_name'

```

**Comment by KPostOffice** [comment]
Heya, sorry this was opened during local testing. Closing
