### ISSUE TITLE
Kebechet version manager: NotATriggerException on kebechet_runners.py:210

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/support#138]
## Description
This is an automated issue generated by Kebechet. The version manager threw an exception (NotATriggerException) at
runtime while working on the following repository https://github.com/KPostOffice/khebhut_test

## Traceback
```python
Traceback (most recent call last):
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/version/version.py", line 232, in run
    ) = self._branch_and_update_vers_and_changelog(
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/version/version.py", line 115, in _branch_and_update_vers_and_changelog
    res = self._trigger_update_files(trigger)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/version/version.py", line 95, in _trigger_update_files
    raise NotATriggerException
kebechet.managers.version.exceptions.NotATriggerException

```

**Comment by KPostOffice** [comment]
This should not raise an issue to support. I will make the necessary changes.
