### ISSUE TITLE
Kebechet version manager: GitCommandError on kebechet_runners.py:210

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/support#139]
## Description
This is an automated issue generated by Kebechet. The version manager threw an exception (GitCommandError) at
runtime while working on the following repository https://github.com/KPostOffice/khebhut_test

## Traceback
```python
Traceback (most recent call last):
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/kebechet_runners.py", line 210, in run
    instance.run(**manager_configuration)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/version/version.py", line 232, in run
    ) = self._branch_and_update_vers_and_changelog(
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/managers/version/version.py", line 115, in _branch_and_update_vers_and_changelog
    with cloned_repo(self) as repo:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/kpostlet/thoth-all/thoth-station/kebechet/kebechet/utils.py", line 78, in cloned_repo
    repo = git.Repo.clone_from(repo_url, repo_path, branch=branch, **clone_kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet-Lq74sYKo/lib/python3.8/site-packages/git/cmd.py", line 501, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=master git@github.com:KPostOffice/khebhut_test.git /tmp/tmpbzdf9v2p
  stderr: 'Cloning into '/tmp/tmpbzdf9v2p'...
fatal: Remote branch master not found in upstream origin
'

```

**Comment by KPostOffice** [comment]
This issue is fixed by https://github.com/thoth-station/kebechet/pull/880/files
