### ISSUE TITLE
`thamos install` fails...

### ISSUE THREAD

**Issue by goern** [thoth-station/support#201]
**Describe the bug**
```
$ thamos install 
2022-03-15 10:49:38,987 [1885724] WARNING  thamos.lib: Development dependencies will not be installed - see https://thoth-station.ninja/j/no_dev
2022-03-15 10:49:38,987 [1885724] INFO     thamos.lib: Installing requirements for runtime environment 'ubi8'
2022-03-15 10:49:38,987 [1885724] INFO     thamos.lib: Using 'pipenv' installation method to install dependencies stated in '/tmp/tmp.tQZkSHvSQI/cli-examples'
2022-03-15 10:49:38,987 [1885724] INFO     thamos.config: Creating virtual environment
failed to find interpreter for Builtin discover of python_spec='3.8'
$ thamos version 
Thamos Client version: 1.27.2
Thoth API https://khemenu.thoth-station.ninja/api/v1: 0.34.10
$ python3 --version 
Python 3.9.7
$ which python3 
/usr/bin/python3
$ rpm -qf /usr/bin/python3 
python3-3.9.7-1.fc34.x86_64

```

**To Reproduce**
1. follow https://redhat-scholars.github.io/managing-vulnerabilities-with-thoth/managing-vulnerabilities-with-thoth/01-run-application.html
2. `thamos install` fails

**Expected behavior**
... shall just work

**Additional Context**
This is running in a fedora 34 toolbox created using `toolbox create fedora`

/priority critical-urgent
/assign @mayaCostantini

**Comment by goern** [comment]
hmm, no, Fedora toolbox 34 has just python 3.9. `dnf install python3.8` fixes the problem

maybe it needs a better error message with an actionable item?

**Comment by goern** [comment]
so `thamos install` works if py38 is installed, running the application still uses py3.9:

```
thamos run --no-pedantic ./game_of_life.py  
Traceback (most recent call last):
  File "./game_of_life.py", line 20, in <module>
    import click
ModuleNotFoundError: No module named 'click'
2022-03-15 21:03:05,777 [2233232] CRITICAL root: Traceback (most recent call last):
  File "/home/goern/.local/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/home/goern/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/goern/.local/lib/python3.9/site-packages/rich_click/rich_click.py", line 594, in main
    return super().main(*args, standalone_mode=False, **kwargs)
  File "/home/goern/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/goern/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/goern/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/goern/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/goern/.local/lib/python3.9/site-packages/thamos/cli.py", line 503, in run
    subprocess.run(cmd, universal_newlines=True, check=True, env=process_env)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmp.tQZkSHvSQI/cli-examples/.venv/bin/python3', './game_of_life.py']' returned non-zero exit status 1.

```

**Comment by codificat** [comment]
@goern is this still relevant?

**Comment by goern** [comment]
sorry for the delay. it look like 1.27.9 seems to fix the error and gives an informative `Running Python version 3.10, but Pipfile.lock requires Python version 3.8`
/close
