### ISSUE TITLE
Kebechet thoth-advise manager: AttributeError on kebechet_runners.py:212

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/support#250]
## Description
This is an automated issue generated by Kebechet v1.10.1. The thoth-advise manager threw an exception (AttributeError)
at runtime while working on the following repository https://github.com/thoth-station/ps-nlp

## Traceback
```python
Traceback (most recent call last):
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/kebechet_runners.py", line 212, in run
    instance.run(**manager_configuration)
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 414, in run
    for k,v in res[0].iteritems:
AttributeError: 'dict' object has no attribute 'iteritems'

```

**Comment by KPostOffice** [comment]
I am closing these as they were created from local testing from @shreekarSS , this makes it difficult to tell whether they are due to an existing bug or due to bugs introduced during local development. I've opened a PR to have this behavior configurable and off by default.
