### ISSUE TITLE
Kebechet thoth-advise manager: FileNotFoundError on kebechet_runners.py:212

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/support#252]
## Description
This is an automated issue generated by Kebechet v1.10.1. The thoth-advise manager threw an exception (FileNotFoundError)
at runtime while working on the following repository https://github.com/thoth-station/ps-nlp

## Traceback
```python
Traceback (most recent call last):
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/kebechet_runners.py", line 212, in run
    instance.run(**manager_configuration)
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 415, in run
    opened_merge = self._open_merge_request(
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 167, in _open_merge_request
    self._git_push(":pushpin: " + commit_msg, branch_name, files, force_push=True)
  File "/home/shreekarSS/wip/issue_151/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 124, in _git_push
    self.repo.index.add(files)
  File "/home/shreekarSS/.local/share/virtualenvs/kebechet-7-d_xeZp/lib/python3.8/site-packages/git/index/base.py", line 772, in add
    entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
  File "/home/shreekarSS/.local/share/virtualenvs/kebechet-7-d_xeZp/lib/python3.8/site-packages/git/util.py", line 102, in wrapper
    return func(self, *args, **kwargs)
  File "/home/shreekarSS/.local/share/virtualenvs/kebechet-7-d_xeZp/lib/python3.8/site-packages/git/index/util.py", line 103, in set_git_working_dir
    return func(self, *args, **kwargs)
  File "/home/shreekarSS/.local/share/virtualenvs/kebechet-7-d_xeZp/lib/python3.8/site-packages/git/index/base.py", line 657, in _entries_for_paths
    entries_added.append(self._store_path(filepath, fprogress))
  File "/home/shreekarSS/.local/share/virtualenvs/kebechet-7-d_xeZp/lib/python3.8/site-packages/git/index/base.py", line 615, in _store_path
    st = os.lstat(filepath)     # handles non-symlinks as well
FileNotFoundError: [Errno 2] No such file or directory: 'Pipfile.lock'

```

**Comment by codificat** [comment]
Similar issue closed in the past as non-reproducible: #164

**Comment by KPostOffice** [comment]
I think this might actually be fixed by https://github.com/thoth-station/kebechet/commit/b405c224bea8763c94699c180ecf66b2aac18791

**Comment by KPostOffice** [comment]
Marking as not reproducible. If someone wants to take the time to try to reproduce this error feel free, but I believe the linked commit from Shree fixes it by making sure the overlay dir is prepended to the Pipfile.lock to be commited.

**Comment by codificat** [comment]
ok!

/triage duplicate
/close
