### ISSUE TITLE
Kebechet thoth-advise manager: ValueError on kebechet_runners.py:212

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/support#256]
## Description
This is an automated issue generated by Kebechet v1.10.1. The thoth-advise manager threw an exception (ValueError)
at runtime while working on the following repository https://github.com/shreekarSS/ps-nlp

## Traceback
```python
Traceback (most recent call last):
  File "/home/sshreeka/wip/issue_151/kebechet/kebechet/kebechet_runners.py", line 212, in run
    instance.run(**manager_configuration)
  File "/home/sshreeka/wip/issue_151/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 390, in run
    res = lib.get_analysis_results(analysis_id)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/lib.py", line 118, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/lib.py", line 1064, in get_analysis_results
    response = _retrieve_analysis_result(method, analysis_id)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/lib.py", line 276, in _retrieve_analysis_result
    return retrieve_func(analysis_id)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/thoth/advise_api.py", line 53, in get_advise_python
    (data) = self.get_advise_python_with_http_info(analysis_id, **kwargs)  # noqa: E501
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/thoth/advise_api.py", line 112, in get_advise_python_with_http_info
    return self.api_client.call_api(
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 620, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/models/adviser_result_response.py", line 46, in __init__
    self.result = result
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-br4_vW2r/lib/python3.8/site-packages/thamos/swagger_client/models/adviser_result_response.py", line 88, in result
    raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `result`, must not be `None`

```

**Comment by KPostOffice** [comment]
I am closing these as they were created from local testing from @shreekarSS , this makes it difficult to tell whether they are due to an existing bug or due to bugs introduced during local development. I've opened a PR to have this behavior configurable and off by default.
