### ISSUE TITLE
Kebechet thoth-advise manager: ApiException on kebechet_runners.py:212

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/support#266]
## Description
This is an automated issue generated by Kebechet v1.10.1. The thoth-advise manager threw an exception (ApiException)
at runtime while working on the following repository https://github.com/shreekarSS/ps-ip

## Traceback
```python
Traceback (most recent call last):
  File "/home/sshreeka/wip/issue_1069/kebechet/kebechet/kebechet_runners.py", line 212, in run
    instance.run(**manager_configuration)
  File "/home/sshreeka/wip/issue_1069/kebechet/kebechet/managers/thoth_advise/thoth_advise.py", line 374, in run
    res = lib.get_analysis_results(analysis_id)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/lib.py", line 118, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/lib.py", line 1064, in get_analysis_results
    response = _retrieve_analysis_result(method, analysis_id)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/lib.py", line 276, in _retrieve_analysis_result
    return retrieve_func(analysis_id)
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/thoth/advise_api.py", line 53, in get_advise_python
    (data) = self.get_advise_python_with_http_info(analysis_id, **kwargs)  # noqa: E501
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/thoth/advise_api.py", line 112, in get_advise_python_with_http_info
    return self.api_client.call_api(
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 148, in __call_api
    response_data = self.request(
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 338, in request
    return self.rest_client.GET(url,
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/rest.py", line 228, in GET
    return self.request("GET", url,
  File "/home/sshreeka/.local/share/virtualenvs/kebechet-D8KYIk9F/lib/python3.8/site-packages/thamos/swagger_client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
thamos.swagger_client.rest.ApiException: (400)
Reason: BAD REQUEST
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn', 'date': 'Tue, 26 Jul 2022 21:24:09 GMT', 'content-type': 'application/json', 'content-length': '272', 'x-thoth-version': '0.35.2', 'x-user-api-service-version': '0.35.2+messaging.0.16.1.storages.0.72.1.common.0.36.2.python.0.16.10', 'x-thoth-search-ui-url': 'https://thoth-station.ninja/search/', 'access-control-allow-origin': '*', 'set-cookie': '99770cb82864be05282857f803e02327=71283d09b941169601817f89b67f6781; path=/; HttpOnly; Secure; SameSite=None'})
HTTP response body: b'{\n  "error": "Analysis was not successful",\n  "parameters": {\n    "analysis_id": "adviser-220726212147-4005fc9ae7e18670"\n  },\n  "status": {\n    "finished_at": "2022-07-26T21:22:22Z",\n    "reason": null,\n    "started_at": "2022-07-26T21:21:48Z",\n    "state": "error"\n  }\n}\n'


```

**Comment by goern** [comment]
is this still valid?

/sig devsecops

**Comment by shreekarSS** [comment]
> is this still valid?
> 
> /sig devsecops

This issue is fixed in https://github.com/thoth-station/kebechet/pull/1098, we can close this.
