### ISSUE TITLE
Kebechet info manager: GitCommandError on kebechet_runners.py:212

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/support#267]
## Description
This is an automated issue generated by Kebechet v1.10.1. The info manager threw an exception (GitCommandError)
at runtime while working on the following repository https://github.com/shreekarSS/nlp-first-steps

## Traceback
```python
Traceback (most recent call last):
  File "/home/user/kebechet/kebechet_runners.py", line 212, in run
    instance.run(**manager_configuration)
  File "/home/user/kebechet/managers/info/info.py", line 55, in run
    with cloned_repo(self, depth=1) as repo:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/kebechet/utils.py", line 120, in cloned_repo
    repo = _clone_repo_and_set_vals(repo_url, repo_path, **clone_kwargs)
  File "/home/user/kebechet/utils.py", line 60, in _clone_repo_and_set_vals
    repo = git.Repo.clone_from(repo_url, repo_path, **clone_kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.8/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --depth=1 git@github.com:shreekarSS/nlp-first-steps.git /tmp/tmpl6taa_0h
  stderr: 'Cloning into '/tmp/tmpl6taa_0h'...
No user exists for uid 1042
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'

```

**Comment by KPostOffice** [comment]
I am closing these as they were created from local testing from @shreekarSS , this makes it difficult to tell whether they are due to an existing bug or due to bugs introduced during local development. I've opened a PR to have this behavior configurable and off by default.
